NODE_RPC_URL="http://127.0.0.1:8545"
DEPLOYER="0xac0974bec39a17e36ba4a6b4d238ff944bacb478cbed5efcae784d7bf4f2ff80"
BYTES="Bytes"
MEMORY="Memory"
SCALECODEC="ScaleCodec"
COMPACTTYPES="CompactTypes"
CALLENCODER="CallEncoder"
XCMBUILDER="XCMBuilder"

forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/utils/${MEMORY}.sol:${MEMORY}"
forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/utils/${BYTES}.sol:${BYTES}"
forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/utils/${SCALECODEC}.sol:${SCALECODEC}"
forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/${COMPACTTYPES}.sol:${COMPACTTYPES}"
forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/${CALLENCODER}.sol:${CALLENCODER}"
forge create --rpc-url ${NODE_RPC_URL} --private-key "${DEPLOYER}" "src/${XCMBUILDER}.sol:${XCMBUILDER}"
